---
title: "Analysis"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sjPlot)
```

## Loading final data set from Targets cache

```{r loading data}
d <- targets::tar_read("final_data")
```

## Modeling positivity discprepancy
```{r modeling pos}
d$isChat[is.na(d$isChat)] <- 0
d$is_teacher <- d$is_teacher %>% as.factor()
d$ss_binary <- d$ss_binary %>% as.factor()
d$liwc_binary <- d$liwc_binary %>% as.factor()
d$tidytext_binary <- d$tidytext_binary %>% as.factor()
d$q[d$q=="other"] <- "ngss"
d$q <- factor(d$q, level=c("ngss", "#NGSSchat", "state-based-hashtags"))
m <- lm(total_discrepancy_pos ~ 
          nwords  + is_teacher + q + 
          ss_ambi + liwc_ambi + tidytext_ambi + 
          favorite_count + retweet_count + ss_binary + liwc_binary + tidytext_binary, d)
tab_model(m, show.icc = TRUE)
```

## Modeling negativity discprepancy

```{r modeling neg}
d$isChat[is.na(d$isChat)] <- 0
d$is_teacher <- d$is_teacher %>% as.factor()
d$ss_binary <- d$ss_binary %>% as.factor()
d$liwc_binary <- d$liwc_binary %>% as.factor()
d$tidytext_binary <- d$tidytext_binary %>% as.factor()
d$q[d$q=="other"] <- "ngss"
d$q <- factor(d$q, level=c("ngss", "#NGSSchat", "state-based-hashtags"))
m <- lm(total_discrepancy_neg ~ 
          nwords  + is_teacher + q + 
          ss_ambi + liwc_ambi + tidytext_ambi + 
          favorite_count + retweet_count + ss_binary + liwc_binary + tidytext_binary, d)
tab_model(m, show.icc = TRUE)
```

## Modeling overall scale discprepancy

```{r modeling scale}
d$isChat[is.na(d$isChat)] <- 0
d$is_teacher <- d$is_teacher %>% as.factor()
d$ss_binary <- d$ss_binary %>% as.factor()
d$liwc_binary <- d$liwc_binary %>% as.factor()
d$tidytext_binary <- d$tidytext_binary %>% as.factor()
d$q[d$q=="other"] <- "ngss"
d$q <- factor(d$q, level=c("ngss", "#NGSSchat", "state-based-hashtags"))
m <- lm(total_discrepancy_scale ~ 
          nwords  + is_teacher + q + 
          ss_ambi + liwc_ambi + tidytext_ambi + 
          favorite_count + retweet_count + ss_binary + liwc_binary + tidytext_binary, d)
tab_model(m, show.icc = TRUE)
```
