---
title: "Analysis"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lmtest)
library(sandwich)
```

## Loading final data set from Targets cache

```{r loading data}
d <- targets::tar_read("C_discrepancy")
```

## Modeling discrapancy

```{r modeling scale}
d$isChat[is.na(d$isChat)] <- 0
#d$is_teacher <- d$is_teacher %>% as.factor()
d$ss_binary <- d$ss_binary %>% as.factor()
d$liwc_binary <- d$liwc_binary %>% as.factor()
d$tidytext_binary <- d$tidytext_binary %>% as.factor()
d$vader_binary <- d$vader_binary %>% as.factor()
d$q[d$q=="other"] <- "ngss"
d$q <- factor(d$q, level=c("ngss", "#NGSSchat", "state-based-hashtags"))

options(scipen=999)

# POS

m <- lm(total_discrepancy_pos ~ 
          nwords  + q + isChat + 
          ss_ambi + liwc_ambi + tidytext_ambi + vader_ambi +
          favorite_count + retweet_count + 
          ss_binary + liwc_binary + tidytext_binary + vader_binary, d)

# summary(m)
# robust standard errors
# coeftest(m, vcov = vcovHC(m, type="HC1"))

png("pos.png")
par(mfrow=c(2,2))
plot(m)
dev.off()

# NEG

m <- lm(total_discrepancy_neg ~ 
          nwords  + q + isChat + 
          ss_ambi + liwc_ambi + tidytext_ambi + vader_ambi +
          favorite_count + retweet_count + 
          ss_binary + liwc_binary + tidytext_binary + vader_binary, d)

# summary(m)
# robust standard errors
# coeftest(m, vcov = vcovHC(m, type="HC1"))

png("neg.png")
par(mfrow=c(2,2))
plot(m)
dev.off()

# SCALE

m <- lm(total_discrepancy_scale ~ 
          nwords  + q + isChat + 
          ss_ambi + liwc_ambi + tidytext_ambi + vader_ambi +
          favorite_count + retweet_count + 
          ss_binary + liwc_binary + tidytext_binary + vader_binary, d)

# summary(m)
# robust standard errors
# coeftest(m, vcov = vcovHC(m, type="HC1"))

png("scale.png")
par(mfrow=c(2,2))
plot(m)
dev.off()

3+3

```
